# Application Configuration
# -------------------
# This configuration file contains settings for:
# 1. Kafka Consumer
# 2. Database Connection
# 3. Thread Pool Management
# 4. Logging Levels
# 5. Cache Configuration

spring:
  # Kafka Configuration
  # ------------------
  # Controls message consumption and processing
  kafka:
    # Kafka cluster connection details
    bootstrap-servers: localhost:9092
    properties:
      # Schema Registry for Avro schema management
      schema.registry.url: http://localhost:8081

    # Consumer specific settings
    consumer:
      group-id: action-items-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      topics:
        action-items: action-items-topic
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        max.poll.interval.ms: 300000
        max.poll.records: 100
        fetch.min.bytes: 1
        fetch.max.wait.ms: 500
        specific.avro.reader: true
    listener:
      ack-mode: MANUAL
      type: SINGLE
      concurrency: 3
      missing-topics-fatal: false
      # Automatically start listeners only when Kafka is available
      auto-startup: false


  datasource:
    url: jdbc:h2:mem:actionitemsdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  # Cache Configuration
  # ------------------
  # Controls caching behavior for master configurations
  cache:
    type: simple
    cache-names:
      - categoryTypeValidation
      - masterConfigurations
    simple:
      spec: maximumSize=1000,expireAfterWrite=1h

logging:
  level:
    com.example: DEBUG
    org.springframework.kafka: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
