# Application Configuration
# -------------------
# This configuration file contains settings for:
# 1. Kafka Consumer
# 2. Database Connection
# 3. Thread Pool Management
# 4. Logging Levels
# 5. Cache Configuration

server:
  port: 18080

spring:
  # Kafka Configuration
  # ------------------
  # Controls message consumption and processing
  kafka:
    # Kafka cluster connection details
    bootstrap-servers: localhost:9092
    properties:
      # Schema Registry for Avro schema management
      schema.registry.url: http://localhost:8081

    # Consumer specific settings
    consumer:
      group-id: action-items-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      topics:
        action-items: action-items-topic
      properties:
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        max.poll.interval.ms: 300000
        max.poll.records: 100
        fetch.min.bytes: 1
        fetch.max.wait.ms: 500
        specific.avro.reader: true
    listener:
      ack-mode: MANUAL
      type: SINGLE
      concurrency: 3
      missing-topics-fatal: false
      # Automatically start listeners only when Kafka is available
      auto-startup: false

  datasource:
    url: jdbc:postgresql://localhost:5432/sample_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    
    hikari:
      pool-name: PostgreSQL-HikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 600000
      #leak-detection-threshold: 60000
      #initialization-fail-timeout: -1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        query:
          plan_cache_max_size: 2048

  h2:
    console:
      enabled: true
      path: /h2-console

  # Cache Configuration
  # ------------------
  # Controls caching behavior for master configurations
  cache:
    type: simple
    cache-names:
      - categoryTypeValidation
      - masterConfigurations
    simple:
      spec: maximumSize=1000,expireAfterWrite=1h

logging:
  level:
    com.example: DEBUG
    org.springframework.kafka: INFO
    com.example.application.config.DatabaseConfig: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: action-items-service 