/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;
/** Possible states of an action item in its lifecycle. */
@org.apache.avro.specific.AvroGenerated
public enum ActionItemStatusAvro implements org.apache.avro.generic.GenericEnumSymbol<ActionItemStatusAvro> {
  OPEN, CLOSE, UNKNOWN, PENDING, IN_PROGRESS, COMPLETED, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActionItemStatusAvro\",\"namespace\":\"com.example.avro\",\"doc\":\"Possible states of an action item in its lifecycle.\",\"symbols\":[\"OPEN\",\"CLOSE\",\"UNKNOWN\",\"PENDING\",\"IN_PROGRESS\",\"COMPLETED\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
